name: Release

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1

    - name: Run tests and linting
      run: |
        npm install
        npm run lint --if-present
        npm test
      env:
        CI: true
